<a href="https://colab.research.google.com/github/Fenissx/Cuaderno-Algebra-Lineal/blob/main/Cuaderno_de_Algebra_Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices

## Nula
Matriz cuyos elementos son cero

\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}

<br>

## Identidad

Si $a_{ij}$ = 0 , $\forall_{ij} \neq j \ \land $ $a_{ij}$ = 1 , $\forall_{ij} = j$

Entonces A se llama I

Ej:

\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}

<br>

## Matriz Diagonal

$a_{ij}$ = 0 , $\forall_{i} \neq j$
\begin{bmatrix}
0 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 1
\end{bmatrix}

<br>

## Matriz Triangulo Superior

Si $a_{ij} = 0, \forall_{i} > j $

Ej:

\begin{bmatrix}
1 & 3 & 2\\
0 & 2 & 4\\
0 & 0 & 1\\
\end{bmatrix}

<br>

## Matriz Triangulo Inferior

Si $a_{ij} = 0, \forall_{i} < j$

\begin{bmatrix}
1 & 0 & 0\\
5 & 7 & 0\\
7 & 6 & 2
\end{bmatrix}

<br>

## Matriz Simétrica

Si $A = A^T$ entonces $A$ se llama simétrica

Ej:
$A=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end{bmatrix}$


$A^T=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end {bmatrix}$

<br>

# Antisimétrica

Ej:

$A=$
$\begin{bmatrix}
1 & 3 & 5\\
-3 & -1 & 6\\
-5 & -6 & 2
\end {bmatrix}$

$A^T=$
$\begin{bmatrix}
1 & -3 & -5\\
3 & -1 & 6\\
5 & 6 & 2
\end{bmatrix}$

$A \neq A^T$ entonces es antisimétrica

<br>

## Operaciones elementales de fila
Se enfoca nuestra atención a una matriz $A_{mxn}$

1. Multiplicación de un escalar por una fila
2. Reemplazar la enésima fila de $A$ por la fila $r+c$ veces la fila $s$
 
$s \neq r$

3. Intercambio de filas

<br>

## Matemáticamente


$i) e(A)rj = c.Arj$

$\forall_{j} = 1,2,3,...,n$

$ii) e(A)rj = Arj + cAsj$

$\forall_{j} = 1, 2, 3,...,n$

$iii) e(A)rj = Asj$

$e(A)sj = Arj$

Ej:

$A=$
$\begin{bmatrix}
1 & -2 & 3\\
2 & 4 & 1\\
0 & 3 & 7
\end{bmatrix}$

<br>

$i) A1j = [1, -2, 3]$

$= 3 [1, -2, 3]$

$= [3, -6, 9]$

<br>

### Realizar:

$$e(A3j) = 3A3j$$

<br>

$ii) e(A2j) = A2j + (-1)A1j$

$e(A2j) = A2j + (-2)[1, -2, 3]$

$= [2, 4, 1] + [-2, 4, -6]$

$= [0, 8, -5]$

<br>

$iii) e(A)rj = Asj$

$e(A)sj = Arj$

<br>

Ej:

$A=$
$\begin{bmatrix}
1 & -2 & 3\\
2 & 4 & 1\\
0 & 3 & 7
\end{bmatrix}$

<br>

$i)A1j = [1, -2, 3]$

$e(A1j) = 3[1, -2, 3]$

$e(A1j) = [3, -6, 9]$

### Realizar:

$$e(A3j) = 3A3j$$

<br>

$ii) e(A2j) = A2j + (-1)A1j$

$e(A2j) = A2j + (-2)[1, -2, 3]$

$= [2, 4, 1] + [-2, 4, -6]$

$= [0, 8, -5]$

### Realizar:
$$e(A3j) = A3j + (-1)A2j$$

<br>

--Definición--
Sea A y B son matrices mxn sobre los Reales. Se dice que la matriz B es equivalente por filas a la matriz A, si B se obtiene de una sucesión finita de operaciones elementales de filas de la matriz A.

$$A \simeq B$$

Una matriz $R_{mxn}$ se llama reducida de filas si:

-El primer elemento $\neq$ 0 de cada fila no nula es 1.

-Cada columna de $R$ que tiene este primer elemento 1 tiene sus otros elementos $\neq$ 0

$$A \simeq B_1 \simeq B_2 ... \simeq B = R$$

Ej:

$R=$
$\begin{bmatrix}
0 & 1 & 0 & 5\\
1 & 0 & 0 & -1\\
0 & 0 & 1 & 2
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 0 & -1\\
0 & 1 & 0 & 5\\
0 & 0 & 1 & 2
\end{bmatrix}$

$ii) e(Arj) = Arj + cAsj , \forall{j} = 1, 2,...n$

Fórmula: Fila Nueva = Fila Antigua - [(Elemento intersección de esa fila con un pivote)]

<br>

### Ejercicio: Transformar

$A=$
$\begin{bmatrix}
2 & 1 & 3 & 0\\
1 & -2 & -1 & 1\\
-1 & 1 & 2 & 1
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 0 & r_{14}\\
0 & 1 & 0 & r_{24}\\
0 & 0 & 1 & r_{34}
\end{bmatrix}$

<br>

## Matriz Reducida

Definición: Una matriz $R_{mxn}$ se llama matriz reducida, escalón por filas ssi:

<br>

a) $R$ es reducida.
b) Toda la fila de $R$ que tiene todos sus elementos ceros (fila nula) está debajo de todas las filas no nulas
c) Si las filas 1, 2,...,r son las filas no nulas de $R$, y si el primer elemento no cero de la fila $i$ esta en la columna $K_i , i = 1,2,...,r$ entonces $K_1 < K_2 < ... < K_r$.

<br>

$$A → B_1 → B_2 → ... → B → R$$

$A=$
$\begin{bmatrix}
1 & 2 & 3 & 4 & 5\\
2 & 3 & 4 & 5 & 6\\
3 & 4 & 5 & 6 & 7\\
4 & 5 & 6 & 7 & 8
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & -1 & -2 & -3\\
0 & 1 & 2 & 3 & 4\\
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0
\end{bmatrix}$

<br>
<br>

Definición: Sea $A_{mxn}$ sobre $K$, si de $A_{mxn}$ obtenemos la $R$ escalonada

1° Rango de $A=$ filas no nulas de $R$

## Operaciones con matrices

### SUMA

$$A_{mxn} + B_{mxn} = C_{mxn}$$

Ej:

$A=$
$\begin{bmatrix}
1 & 2 & 3\\
-1 & -2 & 0
\end{bmatrix}$

$B=$
$\begin{bmatrix}
0 & 1 & -3\\
3 & 2 & 1
\end{bmatrix}$

$A+B=$
$\begin{bmatrix}
1 & 3 & 0\\
2 & 0 & 1
\end{bmatrix}$

<br>

## Producto de una matriz por un escalar

$C * A_{mn} = D_{mxn}$

Ej:

$3$
$\begin{bmatrix}
1 & 2 & 3\\
-1 & -2 & 0
\end{bmatrix}$
$=$
$\begin{bmatrix}
3 & 6 & 9\\
-3 & -6 & 0
\end{bmatrix}$

<br>

## Producto de Matrices

$$A_{mxd} * B_{dxn} = C_{mxn}$$

$\forall{i} = 1,2,3,...,m$

$\forall{j} = 1,2,3,...,d$

$\forall{K} = 1,2,3,...,n$

<br>

$AB = [a_{2j}][b_{jK}] = [c_{iK}]$

Ej:

$A=$
$\begin{bmatrix}
2 & 1 & 5\\
1 & 3 & 2
\end{bmatrix}$

$B=$
$\begin{bmatrix}
3 & 4\\
-1 & 2\\
2 & 1
\end{bmatrix}$

$A$x$B=$
$\begin{bmatrix}
15 & 15\\
4 & 12
\end{bmatrix}$

<br>

## Inversion de Matrices

**Def**: Sea $A_{n}$ una matriz cuadrada que opera sobre los $R$; si existe una matriz $B_{n}$ cuadrada tal que $AB = BA = I$

A la matriz $B$ se dice que es inversa de $A$ y $A$ es una matriz inversible; por lo que:

$$B=A^{-1}$$

*Entonces*

$$AA^{-1}=A^{-1}A=I$$

*Colorario*

$A^{-1}$ es la inversa de $A$ y $A$ es la inversa de $A^{-1}$

*Teorema*

Si $A$ es inversible entonces $(A^{-1})^{-1}=A$

*Teorema*

Si $A$ y $B$ son inversibles entonces su producto es inversible y además: $(AB)$ también es inversible y además:
$$(AB)^{-1}=B^{-1}A^{-1}$$

### Demostración

$$(AB)(AB)^{-1}=ABB^{-1}A^{-1}$$
$$=AIA^{-1}$$
$$=AA^{-1}$$
$$=I$$

**Si dos matrices son inversibles, el producto es inversible**

Ej:

$A=$
$\begin{bmatrix}
2 & -1\\
1 & 3
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
2 & -1 & 1 & 0\\
1 & 3 & 0 & 1
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
2 & -1 & 1 & 0
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
0 & -7 & 1 & -2
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
0 & 1 & -1/7 & 2/7
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 3/7 & 1/7\\
0 & 1 & -1/7 & 2/7
\end{bmatrix}$

→**entonces $A$ es inversible**

**Nota:** Si $R \neq I$ no ha inversa

<br>

## Matriz Ortogonal

Si $AA^{T} = D$

→ $A$ es Ortogonal

<br>

## Matriz Ortonormal
Si $AA^{T} = I$

→ $A$ es Ortonormal

<br>

## Determinantes

**Def:** El determinante de una función es definida en la siguiente forma:

$$detA \equiv |A|$$

Siendo $A$ una matriz de orden $n^{-1}$ de que se obtiene de la matriz $A$ eliminando la fila $i$ y la columna $j$, a estos determinantes se les llama menores porque son de menor dimensión a la matriz $A$. Los $a_{ij}$ pueden corresponder a elementos de una fila o columna

Ej:

### Matriz de Orden 2 *(menor orden de todos)*

$|A|=$
$\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}$
$= a_{11} a_{22} - a_{21}a_{12} $

### Matriz de Orden 3

$|A_3|=$
$\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{bmatrix}$
$=(-1)^{1+1} a_{11}$
$\begin{bmatrix}
a_{22} & a_{23}\\
a_{32} & a_{33}
\end{bmatrix}$
$+ (-1)^{2+1} a_{21}$
$\begin{bmatrix}
a_{12} & a_{13}\\
a_{32} & a_{33}
\end{bmatrix}$
$+ (-1)^{3+1} a_{31}$
$\begin{bmatrix}
a_{12} & a_{13}\\
a_{22} & a_{23}
\end{bmatrix}$

Ej:

$A=$
$\begin{bmatrix}
1 & -1 & 1\\
1 & 2 & 1\\
1 & 3 & 2
\end{bmatrix}$
$=1$
$\begin{bmatrix}
2 & 1\\
3 & 2
\end{bmatrix}$
$-1$
$\begin{bmatrix}
-1 & 1\\
3 & 2
\end{bmatrix}$
$+1$
$\begin{bmatrix}
-1 & 1\\
2 & 1
\end{bmatrix}$
$=1-(-5)+(-3)=1+5-3=3$

<br>

## Sistemas de ecuaciones

Los sistemas de ecuaciones en matrices son una forma eficiente de resolver conjuntos de ecuaciones lineales. Se representan las incógnitas y los coeficientes en forma de matrices. Por ejemplo, el sistema de ecuaciones lineales:

\begin{cases}
2x+3y=8\\
4x-2y=2
\end{cases}

→ Se puede representar matricialmente como:

\begin{bmatrix}
2 & 3 & x & 8\\
4 & -2 & y & 2
\end{bmatrix}

<br>

## Factorización LU

La **factorización LU** es un método para descomponer una matriz en el producto de dos matrices: una matriz triangular inferior ($L$) y una matriz triangular superior ($U$).

Ej:

$A=$
$\begin{bmatrix}
2 & 1 & 3\\
4 & 0 & 2\\
1 & 3 & 1
\end{bmatrix}$

→ La factorización LU de esta matriz implica encontrar dos matrices $L$ y $U$ tal que $A = LU$. La matriz $L$ es triangular inferior con unos en la diagonal principal, y la matriz $U$ es triangular superior.

Después de aplicar el método de factorización LU a la matriz $A$, obtenemos:

$L=$
$\begin{bmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
1/2 & 1 & 1
\end{bmatrix}$

$U=$
$\begin{bmatrix}
2 & 1 & 3\\
0 & -2 & -4\\
0 & 0 & -1
\end{bmatrix}$

In [ ]:
#Importar libreria numpy
import numpy as np

#Creando Matrices A y B
A = np.array([[2, 1, 5],[1,3,2],[3,2,2]])
B = np.array([[3, 4],[-1, 2],[2, 1]])
C = np.array([[1, 2, 3],[4, 5, 6],[1,5,3]])

#Suma de las Matrices A y B (se requiere matrices de las mismas dimensiones)
S = A + C
print(S)

#Multiplicación de las Matrices A y B
M = np.dot(A,B)
print(M)

#Inversa de Matrices A y B
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)
print(A_inv)
print(C_inv)

#Importar librería scipy
import scipy.linalg

#Obtener descomposición LU de matrices A y B
P, L, U = scipy.linalg.lu(A)
P1, L1, U1 = scipy.linalg.lu(B)
print(P,L,U,P1,L1,U1)

#Reducida de las Matrices
import sympy as sym

D=sym.Matrix([[2,1,0],[3,-2,1],[-2,1,1]])
D.rref(pivots=False)

[[3 3 8]
 [5 8 8]
 [4 7 5]]
[[15 15]
 [ 4 12]
 [11 18]]
[[-0.07407407 -0.2962963   0.48148148]
 [-0.14814815  0.40740741 -0.03703704]
 [ 0.25925926  0.03703704 -0.18518519]]
[[-0.83333333  0.5        -0.16666667]
 [-0.33333333  0.          0.33333333]
 [ 0.83333333 -0.16666667 -0.16666667]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.66666667 -0.14285714  1.        ]] [[3.         2.         2.        ]
 [0.         2.33333333 1.33333333]
 [0.         0.         3.85714286]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[ 1.          0.        ]
 [-0.33333333  1.        ]
 [ 0.66666667 -0.5       ]] [[3.         4.        ]
 [0.         3.33333333]]


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

# Espacios Vectoriales

Un **espacio vectorial** es un conjunto no vacío $V$ de objetos, llamados **vectores**, en el que se han definido dos operaciones: la suma y el producto por un escalar (número real) sujetas a los diez axiomas que se dan a continuación. Los axiomas deben ser válidos para todos los vectores $u$, $v$ y $w$ en $V$ y todos los escalares $α$ y $β$ reales.

Llamamos $u + v$ a la suma de vectores en $V$, y $αv$ al producto de un número real α por un vector $v ∈ V$.

### Axiomas

1. $u+v ∈ V$
2. $u+v=v+u$
3. $(u+v)+w=u+(v+w)$
4. Existe un vector nulo $0_{V} ∈ V$ tal que $v+0_{V}=v$
5. Para cada $v$ en $V$, existe un opuesto $(-v) ∈ V$ tal que $v+(-v)=0_{V}$
6. $αv ∈ V$
7. $α(u+v)=αu+αv$
8. $(α+β)v=αv+βv$
9. $α(βv)=(αβ)v$
10. $1v=v$
 
### Propiedades

1. $0_{u}=0_{V}$
2. $α0_{V}=0_{V}$
3. $(-α)u=-(αu)$
→ En particular, para $α=1:(-1)u=-u$
4. $αu=0_{V} ⟹ α=0$  ó  $u=0_{V}$

<br>

## Subespacios vectoriales

Sea $V$ un espacio vectorial y $W$ un subconjunto no vacío de $V$.
$W$ es un subespacio de $V$ si $W$ es en sí mismo un espacio vectorial con las mismas operaciones (suma de vectores y producto por un escalar) definidas en $V$.

Ej:

$W=\{(x_{1},x_{2} ∈ R^{2}: x_{2}=3x_{1}\}$ ¿Es un subespacio vectorial de $R^{2}$?

Primero analicemos el conjunto $W$. Son todos vectores de $R^{2}$ tales que la segunda componente es el triple de la primera:

$$(x_{1},3x_{1})=x_{1}(1,3)$$

$W$ es la recta que pasa por el origen y tiene vector director $(1,3)$, o sea la recta de ecuación $y=3x$

Para decidir si $W$ es un subespacio de $R^{2}$ habría que verificar que se cumplen los axiomas del 1 al 10. En este caso se **cumplen**.

<br>

## Bases y Dimensiones

Se llama base de un espacio (o subespacio) vectorial a un conjunto
linealmente independiente que sea a la vez sistema generador de dicho espacio o
subespacio.

### Propiedades de las bases

1. Una base de $S$ es un sistema generador minimal de $S$ (lo más pequeño posible).
2. Además es un conjunto independiente maximal dentro de $S$ (lo más grande posible).
3. Una base de $S$ permite expresar todos los vectores de $S$ como combinación lineal de ella,
de manera única para cada vector.

### Ejemplos de bases

**1. La base canónica de $R^{n}$**
$$e_{1}=(1,0,...,0)$$
$$e_{2}=(0,1,...,0)$$
$$...$$
$$e_{n}=(0,0,...,1)$$

-Son linealmente independientes porque forman un determinante no nulo.

-Son sistema generador de $R^{n}$ porque todo vector $(a_{1},a_{2},...,a_{n})∈R^{n}$

<br>

**2. Otra base de $R^{3}$ distinta de la canónica:** $(1,0,0),(1,1,0),(0,2,-3)$.

-Son linealmente independientes porque forman un determinante no nulo.

-Son sistema generador de $R^{3}$ porque cualquier vector $(a,b,c)$ se puede poner como combinacion lineal de ellos. En efecto, dado $(a,b,c)$, buscamos $α,β$ y que satisfagan:

$$(a,b,c)=α(1,0,0)+γ(0,2,-3)$$

Se obtiene un sistema:

\begin{cases}
α+β=a\\
β+2γ=b\\
-3γ=c
\end{cases}

<br>

**3.** $(1,2,3), (4,5,6), (7,8,9)$ en $R^{3}$ **no forman base porque no son linealmente independientes (su determinante es nulo).**

<br>

**4. Base de un subespacio. En $R^{3}$, consideremos el subespacio** $S=$plano$XY$. **Veamos que los vectores** $(3,2,0), (1,-1,0)$ **forman una base de** $S$**.**

<br>

## Dimensión

Todas las bases de un mismo espacio o subespacio tienen el mismo número de vectores.
Se llama dimensión de dicho espacio o subespacio.

<br>

### Ejemplos de Dimensión

1. $R^{n}$ tiene dimension $n$, pues tiene una base de $n$ elementos.

2. $M_{2x2}$ ={matrices 2x2 con terminos reales} tiene dimensión 4. Una base de $M_{2x2}$ es:

$\begin{bmatrix}
1 & 0\\
0 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 1\\
0 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 0\\
1 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 0\\
1 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 0\\
0 & 1
\end{bmatrix}$

3. $P_{2}=${polinomios de grado <= 2 con coeficientes reales} tiene dimension 3. Una base de $P_{2}$ es, por ejemplo, la formada por los tres polinomios siguientes:

$1+0x+0x^{2} , 0+x+0x^{2} , 0+0x+x^{2}$ (es decir, los polinomios $1, x, x^{2}$).

Otra base: $1+2x+3x^{2} , 4+x^2 , 3-x-5x^2$

<br>

### Propiedades de la dimensión

1. Significado físico de la dimensión: los planos tienen dimensión 2, las rectas dimensión 1, el punto dimensión 0. El subespacio $\{0\}$ es el único que tiene dimensión 0.
2. La dimensión de un subespacio en $R^{n}$, coincide con el número de parámetros libres en
su forma paramétrica.
3. Si $S$ y $T$ son subespacios y $S$ está contenido en $T$, entonces $dim S <= dim T$. Además, si se da la igualdad, $dim S = dim T$, ambos espacios han de coincidir.
4. El rango de una familia de vectores, es igual a la dimensión del subespacio que generan.
Es decir: si $v1,v2,. . . v_{n}$ generan un cierto subespacio $S$, y si el rango de dicho conjunto es $r$, entonces $dim S = r$. (Si un cierto conjunto de vectores tienen rango 2, entonces generan un plano; etc.)

### Ejemplo:

En $R^{3}$, sea $S$ el subespacio generado por: $(1,0,2), (0,–1,–2), (3,3,3), (2,2,0)$. Observamos que el rango de este conjunto (= rango de la matriz que forman, por filas o por columnas) es 3. Así por la propiedad 4, tenemos que $dim S = 3$. Pero como estamos en $R^{3}$, por la propiedad 3 ha de ser $S=R^{3}$.

# Ortogonalización y Ortonormalización

## Proceso de Gram-Schmidt

--Explicación--

# Ejercicios
a) Determine si los siguientes conjuntos de vectores en $R^n$ es ortogonal, si es ortogonal determine si es también ortonormal y determine si es base para $R^n$

$1) v_1 = \{(2,-4),(2,1)\}$

$2) v_2 = \{(3,2),(-4,-6)\}$

$3) v_3 = \{(4,-1,1),(-1,0,4),(-4,-17,-1)\}$

b)En los siguientes ejercicios use el proceso de $\textbf{Gram-Schmidt}$ para transformar la base dada para $R^n$ en una base ortonormal.

$1) v_1 = \{(3,4),(1,0)\}$

$2) v_2 = \{(0,1),(-4,-8)\}$

$3) v_3 = \{(1,-2,-2),(-2,2,1),(2,-1,2)\}$

In [ ]:
#Ejercicio 1

import numpy as np

#Definiendo vectores v1 y v2
v1=np.array([2,-4])
v2=np.array([2,1])

#Producto punto de los vectores v1 y v2
u=np.dot(v1,v2)
print(u)

#Verificar si es ortonormal (si las magnitudes sale diferente de 1, entonces no es ortonormal)
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

#Verificar si el conjunto es una base para R^n
M = np.array([v1,v2])
det = np.linalg.det(M)
print(det)

# Conicas

**Definición:** El lugar geométrico de los puntos cuya relación de distancias a un punto y una recta fijos es constante recibe el nombre de sección cónica o simplemente cónica.

\begin{cases}
Punto Fijo → Foco\\
Recta Fija → Directriz\\
Relación Constante → Excentricidad (e)
\end{cases}

<br>

**Excentricidad**

$$e=\frac{c}{a}=\frac{\sqrt{a^2+b^2}}{a};e>1$$

<br>

## Categorías

Si $e<1$, la cónica se llama **Elipse**

Si $e=1$, la cónica se llama **Parábola**

Si $e>1$, la cónica se llama **Hipérbola**

<br>

## Parábola

### Ecuación de la parábola

**Foco a la derecha de directriz:**

$$(y-k)^{2}=4a(x-h)$$

**Directriz encima de foco**

$$(x-h)^{2}=-4a(y-k)$$

**Foco a la izquierda de directriz**

$$(y-k)^{2}=-4a(x-h)$$

**Foco encima de directriz**

$$(x-h)^{2}=4a(y-k)$$

<br>

## Elipse

### Ecuación de la elipse

$$\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$$

Si los focos fueran coordenadas (0,c) y (0,-c), el Eje Mayor estaría sobre el eje $y$ entonces la ec. sería:

$$\frac{x^2}{b^2}+\frac{y^2}{a^2}=1$$

<br>

**Ecs. de las directrices $D'D'$ y $DD$ respectivamente**

$$x+\frac{a}{e}=0$$y$$x-\frac{a}{e}=0$$

<br>

Se denomina **latus rectum** de la elipse a la cuerda perpendicular al eje mayor por uno de los focos, su longitud es $\frac{2b^{2}}{a}$

<br>

Si el centro de la elipse fuese el punto $(h,k)$ y el eje mayor tiene la dirección del eje $x$, la ecuación de la elipse seria igual a:

$$\frac{(x-h)^2}{a^2}+\frac{(y-k)^2}{b^2}=1$$
→Eje mayor perpendicular al eje $x$
$$\frac{(x-h)^2}{b^2}+\frac{(y-k)^2}{a^2}=1$$
→Eje mayor perpendicular al eje $y$

<br>

**Ecuacion general de la elipse**

$$Ax^2+By^2+Dx+Ey+F=0$$

<br>

## Hipérbola

### Ecuación de la hipérbola

$$\frac{x^2}{a^2}-\frac{y^2}{b^2}=1$$

$$c^2-a^2=b^2$$

**Focos tienen coordenadas**

$F(c,0)$ y $F'(-c,0)$

Distancia entre $F$ y $F'$ es igual a $2a$

<br>

**Ecs. directrices DD'**

$$x=±\frac{a}{e}$$

→ Focos están sobre eje $x$

$$y=±\frac{a}{e}$$

→ Focos están sobre eje $y$

<br>

**Ecs. asíntotas**

$$y=±\frac{b}{a}x$$

→ Cuando el eje real es $x$

$$y=±\frac{a}{b}x$$

→ Cuando el eje real es $y$

<br>

*Si el centro de la hipérbola es el pto coordenadas (h,k):*

$$\frac{(x-h)^2}{a^2}-\frac{(y-k)^2}{b^2}=1$$

→ Eje real paralelo al eje $x$

$$\frac{(y-k)^2}{a^2}-\frac{(y-k)^2}{b^2}=1$$

→ Eje real paralelo al eje $y$

<br>

### Forma General de la Ec. de la Hipérbola

$$Ax^2-By^2+Dx+Ey+F=0→$$ siendo $A$ y $B$ del mismo signo.

# Transformaciones Lineales y Vectores Propios

## Transformaciones Lineales

En primer lugar, una transformación lineal es una función. Por ser función, tiene su dominio y su codominio, con la particularidad de que éstos son espacios vectoriales. Tenemos dos espacios vectoriales $V$ y $W$, y una función que va de $V$ a $W$. O sea una regla de asignación que transforma vectores de $V$ en vectores de $W$. Pero no toda función que transforme vectores de $V$ en vectores de $W$ es una transformación lineal. Debe cumplir ciertas condiciones:

$F: V→W$ es una transformación lineal ssi:

1. $F(u+v)=F(u)+F(v)$ , $ ∀ $ $u,v ∈ V$
2. $F(k,v)=k,F(v)$ , $∀v∈V$ , $∀k∈R$

<br>

### Propiedades de una Transformacion Lineal

**Propiedad 1**
La imagen del vector nulo del dominio $0_{v}$ es el vector nulo del codominio $0_{w}$:
$$T(0_V)=0_w$$

**Propiedad 2**
La imagen del vector $-v$ es igual al opuesto de la imagen de $v$:
$$T(-v)=-T(v)$$

**Propiedad 3**
Consideremos $r$ vectores del espacio vectorial $V$:
$$v_1,v_2,...,v_r ∈ V$$

Tomemos una combinación lineal en el dominio:
$$α_1v_1+α_2v_2+α_3v_3+...+α_rv_r$$

Donde $α_i ∈ R$

Si aplicamos la transformación lineal $F$ de $V$ a $W$, teniendo en cuenta las propiedades enunciadas en la definición, resulta:

$$F(α_1v_1+α_2v_2+α_3v_3+...+α_rv_r)=α_1F(v_1)+α$$

Es decir que una transformación lineal <\<transporta\>> combinaciones lineales de $V$ a $W$, conservando los escalares de la combinación lineal.

**Ejemplo:**

Sea $$T(1,0)=(2,1,-1)$$
$$T(0,1)=(1,-1,0)$$

encuentre $T$
$$R^2→R^3$$
$$(x,y)→T(x,y)=?$$

<br>

$$B\{v_1, v_2\} → $$
$B=$
$\begin{cases}
\begin{bmatrix}
1\\
0
\end{bmatrix}
,
\begin{bmatrix}
0\\
1
\end{bmatrix}
\end{cases}$

<br>

$v_1=α_1v_2+α_2v_2$

$v=α$
$\begin{bmatrix}
1\\
0
\end{bmatrix}$
$+α_2$
$\begin{bmatrix}
0\\
1
\end{bmatrix}$

$$x=α_1$$
$$y=α_2$$

$T(\vec{v})=T$
$\left(
    \begin{bmatrix}
    x\\
    y
    \end{bmatrix}
\right)$
$=$
$α_1T$
$\left(
  \begin{bmatrix}
  1\\
  0
  \end{bmatrix}
\right)$
$+α_2T$
$\left(
  \begin{bmatrix}
  0\\
  1
  \end{bmatrix}
\right)$

$T$
$\left(
  \begin{bmatrix}
  x\\
  y
  \end{bmatrix}
\right)$
$=$
$α_1$
$\begin{bmatrix}
2\\
1\\
-1
\end{bmatrix}$
$+α_2$
$\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}$

$T$
$\left(
  \begin{bmatrix}
  x\\
  y
  \end{bmatrix}
\right)$
$=x$
$\begin{bmatrix}
2\\
1\\
1
\end{bmatrix}$
$+y$
$\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}$
$=$
$\begin{bmatrix}
2x+4\\
x-y\\
-x
\end{bmatrix}$
